services:
 urlshortener-db:
  image: postgres:15
  ports:
   - 5433:5432
  environment:
    POSTGRES_USER: username123
    POSTGRES_PASSWORD: password123
    POSTGRES_DB: url_shortener
  volumes:
    - urlShortener-data:/var/lib/postgresql/data
  restart: unless-stopped
  command: postgres -c shared_preload_libraries=pg_stat_statements
  healthcheck:
    test: ["CMD-SHELL", "pg_isready -U username123 -d url_shortener"]
    interval: 10s
    timeout: 5s
    retries: 5

 nginx:
  image: nginx:alpine
  ports:
    - 80:80
    - 443:443
  volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./certs:/etc/nginx/certs:ro
  depends_on:
    - url-shortener-backend
    - url-shortener-backend2
    - url-shortener-backend3
    

 redis:
  image: redis:latest
  ports:
    - 6379:6379
  volumes:
    - redis-data:/data
  restart: unless-stopped
  command: redis-server --appendonly yes
 adminer:
  image: adminer:latest
  restart: unless-stopped
  ports:
   - 8081:8080
  depends_on:
   - urlshortener-db   


 url-shortener-backend:
  build: ./backend
  ports:
   - 3004:3000
  env_file:
    - ./backend/.env
  environment:
    REDIS_URL: redis://redis:6379
    APP_NAME: app1
  depends_on:
   urlshortener-db:
    condition: service_healthy
  restart: unless-stopped

 url-shortener-backend2:
  build: ./backend
  ports:
   - 3002:3000
  env_file:
    - ./backend/.env
  environment:
    REDIS_URL: redis://redis:6379
    APP_NAME: app2
  depends_on:
   urlshortener-db:
    condition: service_healthy
  restart: unless-stopped

 url-shortener-backend3:
  build: ./backend
  ports:
   - 3003:3000
  env_file:
    - ./backend/.env
  environment:
    REDIS_URL: redis://redis:6379
    APP_NAME: app3
  depends_on:
   urlshortener-db:
    condition: service_healthy
  restart: unless-stopped
volumes:
 urlShortener-data:
 redis-data: