worker_processes 1;

events {
    worker_connections 1024;
}

http { 
    include mime.types;

    upstream nodejs_cluster {
    least_conn;
    server url-shortener-backend:3000 max_fails=3 fail_timeout=30s;
    server url-shortener-backend2:3000 max_fails=3 fail_timeout=30s;
    server url-shortener-backend3:3000 max_fails=3 fail_timeout=30s;
}

    server {
        listen 443 ssl;
        server_name localhost;

        ssl_certificate /etc/nginx/certs/nginx-selfsigned.crt;
        ssl_certificate_key /etc/nginx/certs/nginx-selfsigned.key;

        location / {
            proxy_pass http://nodejs_cluster;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

    }
}